name: cypress-test-1
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.0
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.7
